// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// pref_select_impl
NumericVector pref_select_impl(DataFrame scores, List serial_pref, int topk);
RcppExport SEXP rPref_pref_select_impl(SEXP scoresSEXP, SEXP serial_prefSEXP, SEXP topkSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< DataFrame >::type scores(scoresSEXP );
        Rcpp::traits::input_parameter< List >::type serial_pref(serial_prefSEXP );
        Rcpp::traits::input_parameter< int >::type topk(topkSEXP );
        NumericVector __result = pref_select_impl(scores, serial_pref, topk);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// grouped_pref_sel_impl
NumericVector grouped_pref_sel_impl(DataFrame data, DataFrame scores, List serial_pref, int topk);
RcppExport SEXP rPref_grouped_pref_sel_impl(SEXP dataSEXP, SEXP scoresSEXP, SEXP serial_prefSEXP, SEXP topkSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP );
        Rcpp::traits::input_parameter< DataFrame >::type scores(scoresSEXP );
        Rcpp::traits::input_parameter< List >::type serial_pref(serial_prefSEXP );
        Rcpp::traits::input_parameter< int >::type topk(topkSEXP );
        NumericVector __result = grouped_pref_sel_impl(data, scores, serial_pref, topk);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// get_hasse_impl
NumericVector get_hasse_impl(DataFrame scores, List serial_pref);
RcppExport SEXP rPref_get_hasse_impl(SEXP scoresSEXP, SEXP serial_prefSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< DataFrame >::type scores(scoresSEXP );
        Rcpp::traits::input_parameter< List >::type serial_pref(serial_prefSEXP );
        NumericVector __result = get_hasse_impl(scores, serial_pref);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
