# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pref_select_impl <- function(scores, serial_pref, topk) {
    .Call('rPref_pref_select_impl', PACKAGE = 'rPref', scores, serial_pref, topk)
}

grouped_pref_sel_impl <- function(data, scores, serial_pref, topk) {
    .Call('rPref_grouped_pref_sel_impl', PACKAGE = 'rPref', data, scores, serial_pref, topk)
}

get_hasse_impl <- function(scores, serial_pref) {
    .Call('rPref_get_hasse_impl', PACKAGE = 'rPref', scores, serial_pref)
}

